
export const {
    FIREBASE_API_KEY: FIREBASEAPIKEY,
    FIREBASE_AUTH_DOMAIN: FIREBASEAUTHDOMAIN,
    FIREBASE_PROJECT_ID: FIREBASEPROJECTID,
    FIREBASE_STORAGE_BUCKET: FIREBASESTORAGEBUCKET,
    FIREBASE_MESSAGING_SENDER_ID: FIREBASEMESSAGINGSENDERID,
    FIREBASE_APP_ID: FIREBASEAPPID,
    FIREBASE_MEASUREMENT_ID: FIREBASEMEASUREMENTID,
    FIREBASE_STROAGE_URL: FIREBASESTROAGEURL,
    MONGO_DB_CONNECTION_URL: MONGODBCONNECTIONURL,
    STRIPE_PUBLISHABLE_KEY: STRIPEPUBLISHABLEKEY,
    STRIPE_SECRET_KEY: STRIPESECRETKEY,
    NEXT_JS_API_URL: APIURL 
} = process.env

export const HEADERS = {
    Accept: '*/*',
    'Content-Type': 'application/json'
}